// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * DatabaseService manages live sql.DB connections to user-specified databases
 * and exposes query and schema operations to the frontend via Wails.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AddForeignKey(connectionID: string, req: $models.AddForeignKeyRequest): $CancellablePromise<void> {
    return $Call.ByID(2805074927, connectionID, req);
}

export function CommitEdits(connectionID: string, edits: $models.RowEdit[]): $CancellablePromise<void> {
    return $Call.ByID(3786378765, connectionID, edits);
}

/**
 * CommitTableEdits runs inserts, edits, and deletes in a single transaction.
 * A foreign-key violation rolls back and returns a non-nil FKViolation with
 * nil error. Any other DB error is returned as a non-nil error.
 */
export function CommitTableEdits(connectionID: string, payload: $models.CommitPayload): $CancellablePromise<$models.FKViolation | null> {
    return $Call.ByID(2369217, connectionID, payload).then(($result: any) => {
        return $$createType1($result);
    });
}

export function Connect(request: $models.ConnectRequest): $CancellablePromise<$models.Connection> {
    return $Call.ByID(1179166949, request).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * ConnectSaved reconnects using stored credentials for the given saved connection ID.
 */
export function ConnectSaved(id: string): $CancellablePromise<$models.Connection> {
    return $Call.ByID(1993146436, id).then(($result: any) => {
        return $$createType2($result);
    });
}

export function CreateIndex(connectionID: string, req: $models.CreateIndexRequest): $CancellablePromise<void> {
    return $Call.ByID(2110351575, connectionID, req);
}

export function CreateSequence(connectionID: string, req: $models.CreateSequenceRequest): $CancellablePromise<void> {
    return $Call.ByID(2334486284, connectionID, req);
}

export function CreateTable(connectionID: string, req: $models.CreateTableRequest): $CancellablePromise<void> {
    return $Call.ByID(3975160955, connectionID, req);
}

export function DeleteRows(connectionID: string, deletes: $models.RowDelete[]): $CancellablePromise<void> {
    return $Call.ByID(1262655243, connectionID, deletes);
}

/**
 * DisconnectConnection closes the live DB connection but keeps the saved entry.
 */
export function DisconnectConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(1763329183, id);
}

export function DropForeignKey(connectionID: string, schema: string, tableName: string, constraintName: string): $CancellablePromise<void> {
    return $Call.ByID(3843004351, connectionID, schema, tableName, constraintName);
}

export function DropIndex(connectionID: string, schema: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2669775156, connectionID, schema, name);
}

export function DropSequence(connectionID: string, schema: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(823908645, connectionID, schema, name);
}

export function DropTable(connectionID: string, schema: string, name: string): $CancellablePromise<void> {
    return $Call.ByID(2932952380, connectionID, schema, name);
}

export function ExecuteQuery(connectionID: string, statement: string): $CancellablePromise<$models.QueryResult> {
    return $Call.ByID(4264516016, connectionID, statement).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ExplainQuery(connectionID: string, statement: string): $CancellablePromise<string[]> {
    return $Call.ByID(3838571932, connectionID, statement).then(($result: any) => {
        return $$createType4($result);
    });
}

export function FetchTable(connectionID: string, schema: string, table: string, where: string, page: number, pageSize: number): $CancellablePromise<$models.QueryResult> {
    return $Call.ByID(379804161, connectionID, schema, table, where, page, pageSize).then(($result: any) => {
        return $$createType3($result);
    });
}

/**
 * GetNextSequenceValues finds columns with nextval() defaults and advances each
 * sequence, returning a map of column name → next value. Callers should treat
 * sequence gaps from discarded rows as acceptable (standard PostgreSQL behaviour).
 */
export function GetNextSequenceValues(connectionID: string, schema: string, table: string): $CancellablePromise<{ [_ in string]?: string }> {
    return $Call.ByID(4032207833, connectionID, schema, table).then(($result: any) => {
        return $$createType5($result);
    });
}

export function GetTableColumns(connectionID: string, schema: string, table: string): $CancellablePromise<$models.ColumnInfo[]> {
    return $Call.ByID(1845361084, connectionID, schema, table).then(($result: any) => {
        return $$createType7($result);
    });
}

export function GetTableDDL(connectionID: string, schema: string, table: string): $CancellablePromise<string> {
    return $Call.ByID(3753861915, connectionID, schema, table);
}

export function InsertRows(connectionID: string, inserts: $models.RowInsert[]): $CancellablePromise<void> {
    return $Call.ByID(2135737537, connectionID, inserts);
}

/**
 * ListColumnTypes returns the types supported by the connected database,
 * grouped by category. For PostgreSQL this queries pg_catalog; for other
 * drivers it returns a curated static list.
 */
export function ListColumnTypes(connectionID: string): $CancellablePromise<$models.TypeGroup[]> {
    return $Call.ByID(1796961020, connectionID).then(($result: any) => {
        return $$createType9($result);
    });
}

/**
 * ListConnections returns all currently open (live) connections.
 */
export function ListConnections(): $CancellablePromise<$models.Connection[]> {
    return $Call.ByID(1316334534).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListForeignKeys(connectionID: string, schema: string): $CancellablePromise<$models.ForeignKeyInfo[]> {
    return $Call.ByID(2155748755, connectionID, schema).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListIndexes(connectionID: string, schema: string): $CancellablePromise<$models.IndexInfo[]> {
    return $Call.ByID(976451507, connectionID, schema).then(($result: any) => {
        return $$createType14($result);
    });
}

export function ListSchemaObjects(connectionID: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(2805913978, connectionID).then(($result: any) => {
        return $$createType16($result);
    });
}

export function ListSequences(connectionID: string, schema: string): $CancellablePromise<$models.SequenceInfo[]> {
    return $Call.ByID(2451052281, connectionID, schema).then(($result: any) => {
        return $$createType18($result);
    });
}

export function PickSQLiteFile(): $CancellablePromise<string> {
    return $Call.ByID(519332286);
}

export function ReadFile(path: string): $CancellablePromise<string> {
    return $Call.ByID(2181123383, path);
}

export function WriteFile(path: string, content: string): $CancellablePromise<void> {
    return $Call.ByID(2476041102, path, content);
}

// Private type creation functions
const $$createType0 = $models.FKViolation.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $models.Connection.createFrom;
const $$createType3 = $models.QueryResult.createFrom;
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = $Create.Map($Create.Any, $Create.Any);
const $$createType6 = $models.ColumnInfo.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.TypeGroup.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType2);
const $$createType11 = $models.ForeignKeyInfo.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = $models.IndexInfo.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = $models.SchemaObject.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = $models.SequenceInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
