// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AddForeignKeyRequest {
    "schema": string;
    "table": string;
    "name": string;
    "column": string;
    "foreignSchema": string;
    "foreignTable": string;
    "foreignColumn": string;
    "onDelete": string;
    "onUpdate": string;

    /** Creates a new AddForeignKeyRequest instance. */
    constructor($$source: Partial<AddForeignKeyRequest> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("foreignSchema" in $$source)) {
            this["foreignSchema"] = "";
        }
        if (!("foreignTable" in $$source)) {
            this["foreignTable"] = "";
        }
        if (!("foreignColumn" in $$source)) {
            this["foreignColumn"] = "";
        }
        if (!("onDelete" in $$source)) {
            this["onDelete"] = "";
        }
        if (!("onUpdate" in $$source)) {
            this["onUpdate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AddForeignKeyRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): AddForeignKeyRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AddForeignKeyRequest($$parsedSource as Partial<AddForeignKeyRequest>);
    }
}

export class ColumnDef {
    "name": string;
    "dataType": string;
    "nullable": boolean;
    "default": string;

    /** Creates a new ColumnDef instance. */
    constructor($$source: Partial<ColumnDef> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("nullable" in $$source)) {
            this["nullable"] = false;
        }
        if (!("default" in $$source)) {
            this["default"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnDef instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnDef {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnDef($$parsedSource as Partial<ColumnDef>);
    }
}

export class ColumnInfo {
    "name": string;
    "dataType": string;
    "isNullable": boolean;
    "columnDefault": string | null;

    /** Creates a new ColumnInfo instance. */
    constructor($$source: Partial<ColumnInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            this["dataType"] = "";
        }
        if (!("isNullable" in $$source)) {
            this["isNullable"] = false;
        }
        if (!("columnDefault" in $$source)) {
            this["columnDefault"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ColumnInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo($$parsedSource as Partial<ColumnInfo>);
    }
}

export class CommitPayload {
    "inserts": RowInsert[];
    "edits": RowEdit[];
    "deletes": RowDelete[];

    /** Creates a new CommitPayload instance. */
    constructor($$source: Partial<CommitPayload> = {}) {
        if (!("inserts" in $$source)) {
            this["inserts"] = [];
        }
        if (!("edits" in $$source)) {
            this["edits"] = [];
        }
        if (!("deletes" in $$source)) {
            this["deletes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CommitPayload instance from a string or object.
     */
    static createFrom($$source: any = {}): CommitPayload {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("inserts" in $$parsedSource) {
            $$parsedSource["inserts"] = $$createField0_0($$parsedSource["inserts"]);
        }
        if ("edits" in $$parsedSource) {
            $$parsedSource["edits"] = $$createField1_0($$parsedSource["edits"]);
        }
        if ("deletes" in $$parsedSource) {
            $$parsedSource["deletes"] = $$createField2_0($$parsedSource["deletes"]);
        }
        return new CommitPayload($$parsedSource as Partial<CommitPayload>);
    }
}

export class ConnectRequest {
    "name": string;
    "driver": string;
    "connectionString": string;

    /**
     * set by PS flow to tag the saved connection
     */
    "planetscaleKey"?: string;

    /**
     * set by Supabase flow to tag the saved connection
     */
    "supabaseKey"?: string;

    /** Creates a new ConnectRequest instance. */
    constructor($$source: Partial<ConnectRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("connectionString" in $$source)) {
            this["connectionString"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ConnectRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectRequest($$parsedSource as Partial<ConnectRequest>);
    }
}

/**
 * Connection is a live (or previously live) connection summary shown in the UI.
 */
export class Connection {
    "id": string;
    "name": string;
    "driver": string;
    "user": string;
    "host": string;
    "database": string;
    "status": string;
    "lastUsed": string;
    "connected": boolean;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("database" in $$source)) {
            this["database"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = "";
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

export class CreateIndexRequest {
    "schema": string;
    "table": string;
    "name": string;
    "columns": string;
    "isUnique": boolean;
    "method": string;

    /** Creates a new CreateIndexRequest instance. */
    constructor($$source: Partial<CreateIndexRequest> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = "";
        }
        if (!("isUnique" in $$source)) {
            this["isUnique"] = false;
        }
        if (!("method" in $$source)) {
            this["method"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateIndexRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateIndexRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateIndexRequest($$parsedSource as Partial<CreateIndexRequest>);
    }
}

export class CreateSequenceRequest {
    "schema": string;
    "name": string;
    "incrementBy": number;
    "startValue": number;
    "minValue": number;
    "maxValue": number;
    "isCycled": boolean;

    /** Creates a new CreateSequenceRequest instance. */
    constructor($$source: Partial<CreateSequenceRequest> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("incrementBy" in $$source)) {
            this["incrementBy"] = 0;
        }
        if (!("startValue" in $$source)) {
            this["startValue"] = 0;
        }
        if (!("minValue" in $$source)) {
            this["minValue"] = 0;
        }
        if (!("maxValue" in $$source)) {
            this["maxValue"] = 0;
        }
        if (!("isCycled" in $$source)) {
            this["isCycled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateSequenceRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateSequenceRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CreateSequenceRequest($$parsedSource as Partial<CreateSequenceRequest>);
    }
}

export class CreateTableRequest {
    "schema": string;
    "name": string;
    "columns": ColumnDef[];

    /** Creates a new CreateTableRequest instance. */
    constructor($$source: Partial<CreateTableRequest> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CreateTableRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): CreateTableRequest {
        const $$createField2_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        return new CreateTableRequest($$parsedSource as Partial<CreateTableRequest>);
    }
}

export class ExecutionPlanStep {
    "id": number;
    "operation": string;
    "object": string;
    "cost": number;
    "rows": number;

    /** Creates a new ExecutionPlanStep instance. */
    constructor($$source: Partial<ExecutionPlanStep> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionPlanStep instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionPlanStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecutionPlanStep($$parsedSource as Partial<ExecutionPlanStep>);
    }
}

/**
 * FKViolation is returned by CommitTableEdits when a foreign-key constraint is
 * violated. The transaction is rolled back; callers should display this rather
 * than treating it as an unexpected error.
 */
export class FKViolation {
    "column": string;
    "value": string;
    "referencedTable": string;

    /** Creates a new FKViolation instance. */
    constructor($$source: Partial<FKViolation> = {}) {
        if (!("column" in $$source)) {
            this["column"] = "";
        }
        if (!("value" in $$source)) {
            this["value"] = "";
        }
        if (!("referencedTable" in $$source)) {
            this["referencedTable"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FKViolation instance from a string or object.
     */
    static createFrom($$source: any = {}): FKViolation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FKViolation($$parsedSource as Partial<FKViolation>);
    }
}

export class ForeignKeyInfo {
    "schema": string;
    "name": string;
    "tableName": string;
    "columnName": string;
    "foreignSchema": string;
    "foreignTable": string;
    "foreignColumn": string;
    "onDelete": string;
    "onUpdate": string;

    /** Creates a new ForeignKeyInfo instance. */
    constructor($$source: Partial<ForeignKeyInfo> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("tableName" in $$source)) {
            this["tableName"] = "";
        }
        if (!("columnName" in $$source)) {
            this["columnName"] = "";
        }
        if (!("foreignSchema" in $$source)) {
            this["foreignSchema"] = "";
        }
        if (!("foreignTable" in $$source)) {
            this["foreignTable"] = "";
        }
        if (!("foreignColumn" in $$source)) {
            this["foreignColumn"] = "";
        }
        if (!("onDelete" in $$source)) {
            this["onDelete"] = "";
        }
        if (!("onUpdate" in $$source)) {
            this["onUpdate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ForeignKeyInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKeyInfo($$parsedSource as Partial<ForeignKeyInfo>);
    }
}

export class IndexInfo {
    "schema": string;
    "name": string;
    "tableName": string;
    "isUnique": boolean;
    "isPrimary": boolean;
    "definition": string;

    /** Creates a new IndexInfo instance. */
    constructor($$source: Partial<IndexInfo> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("tableName" in $$source)) {
            this["tableName"] = "";
        }
        if (!("isUnique" in $$source)) {
            this["isUnique"] = false;
        }
        if (!("isPrimary" in $$source)) {
            this["isPrimary"] = false;
        }
        if (!("definition" in $$source)) {
            this["definition"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): IndexInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexInfo($$parsedSource as Partial<IndexInfo>);
    }
}

export class QueryResult {
    "columns": string[];
    "columnTypes": string[];
    "primaryKeys": string[];
    "rows": { [_ in string]?: string }[];
    "rowIds": string[];
    "durationMs": number;
    "message": string;
    "plan": ExecutionPlanStep[];
    "planLines": string[];
    "objectStats": SchemaObjectSummary[];
    "totalRows": number;
    "pageSize": number;

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("columnTypes" in $$source)) {
            this["columnTypes"] = [];
        }
        if (!("primaryKeys" in $$source)) {
            this["primaryKeys"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("rowIds" in $$source)) {
            this["rowIds"] = [];
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("plan" in $$source)) {
            this["plan"] = [];
        }
        if (!("planLines" in $$source)) {
            this["planLines"] = [];
        }
        if (!("objectStats" in $$source)) {
            this["objectStats"] = [];
        }
        if (!("totalRows" in $$source)) {
            this["totalRows"] = 0;
        }
        if (!("pageSize" in $$source)) {
            this["pageSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType8;
        const $$createField1_0 = $$createType8;
        const $$createField2_0 = $$createType8;
        const $$createField3_0 = $$createType10;
        const $$createField4_0 = $$createType8;
        const $$createField7_0 = $$createType12;
        const $$createField8_0 = $$createType8;
        const $$createField9_0 = $$createType14;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("columnTypes" in $$parsedSource) {
            $$parsedSource["columnTypes"] = $$createField1_0($$parsedSource["columnTypes"]);
        }
        if ("primaryKeys" in $$parsedSource) {
            $$parsedSource["primaryKeys"] = $$createField2_0($$parsedSource["primaryKeys"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        if ("rowIds" in $$parsedSource) {
            $$parsedSource["rowIds"] = $$createField4_0($$parsedSource["rowIds"]);
        }
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField7_0($$parsedSource["plan"]);
        }
        if ("planLines" in $$parsedSource) {
            $$parsedSource["planLines"] = $$createField8_0($$parsedSource["planLines"]);
        }
        if ("objectStats" in $$parsedSource) {
            $$parsedSource["objectStats"] = $$createField9_0($$parsedSource["objectStats"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class RowDelete {
    "schema": string;
    "table": string;
    "rowId": string;

    /** Creates a new RowDelete instance. */
    constructor($$source: Partial<RowDelete> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("rowId" in $$source)) {
            this["rowId"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowDelete instance from a string or object.
     */
    static createFrom($$source: any = {}): RowDelete {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RowDelete($$parsedSource as Partial<RowDelete>);
    }
}

export class RowEdit {
    "schema": string;
    "table": string;
    "rowId": string;
    "changes": { [_ in string]?: string };

    /** Creates a new RowEdit instance. */
    constructor($$source: Partial<RowEdit> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("rowId" in $$source)) {
            this["rowId"] = "";
        }
        if (!("changes" in $$source)) {
            this["changes"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowEdit instance from a string or object.
     */
    static createFrom($$source: any = {}): RowEdit {
        const $$createField3_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("changes" in $$parsedSource) {
            $$parsedSource["changes"] = $$createField3_0($$parsedSource["changes"]);
        }
        return new RowEdit($$parsedSource as Partial<RowEdit>);
    }
}

export class RowInsert {
    "schema": string;
    "table": string;
    "values": { [_ in string]?: string };

    /** Creates a new RowInsert instance. */
    constructor($$source: Partial<RowInsert> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("table" in $$source)) {
            this["table"] = "";
        }
        if (!("values" in $$source)) {
            this["values"] = {};
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowInsert instance from a string or object.
     */
    static createFrom($$source: any = {}): RowInsert {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("values" in $$parsedSource) {
            $$parsedSource["values"] = $$createField2_0($$parsedSource["values"]);
        }
        return new RowInsert($$parsedSource as Partial<RowInsert>);
    }
}

export class SchemaObject {
    "name": string;
    "type": string;
    "schema": string;
    "rows": number;
    "modified": string;

    /** Creates a new SchemaObject instance. */
    constructor($$source: Partial<SchemaObject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("modified" in $$source)) {
            this["modified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaObject instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaObject($$parsedSource as Partial<SchemaObject>);
    }
}

export class SchemaObjectSummary {
    "label": string;
    "count": number;

    /** Creates a new SchemaObjectSummary instance. */
    constructor($$source: Partial<SchemaObjectSummary> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaObjectSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaObjectSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaObjectSummary($$parsedSource as Partial<SchemaObjectSummary>);
    }
}

export class SequenceInfo {
    "schema": string;
    "name": string;
    "lastValue": string;
    "incrementBy": string;
    "minValue": string;
    "maxValue": string;
    "isCycled": boolean;

    /** Creates a new SequenceInfo instance. */
    constructor($$source: Partial<SequenceInfo> = {}) {
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("lastValue" in $$source)) {
            this["lastValue"] = "";
        }
        if (!("incrementBy" in $$source)) {
            this["incrementBy"] = "";
        }
        if (!("minValue" in $$source)) {
            this["minValue"] = "";
        }
        if (!("maxValue" in $$source)) {
            this["maxValue"] = "";
        }
        if (!("isCycled" in $$source)) {
            this["isCycled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SequenceInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): SequenceInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SequenceInfo($$parsedSource as Partial<SequenceInfo>);
    }
}

export class TypeEntry {
    "name": string;
    "description": string;

    /** Creates a new TypeEntry instance. */
    constructor($$source: Partial<TypeEntry> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("description" in $$source)) {
            this["description"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): TypeEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TypeEntry($$parsedSource as Partial<TypeEntry>);
    }
}

export class TypeGroup {
    "label": string;
    "types": TypeEntry[];

    /** Creates a new TypeGroup instance. */
    constructor($$source: Partial<TypeGroup> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("types" in $$source)) {
            this["types"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TypeGroup instance from a string or object.
     */
    static createFrom($$source: any = {}): TypeGroup {
        const $$createField1_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("types" in $$parsedSource) {
            $$parsedSource["types"] = $$createField1_0($$parsedSource["types"]);
        }
        return new TypeGroup($$parsedSource as Partial<TypeGroup>);
    }
}

// Private type creation functions
const $$createType0 = RowInsert.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = RowEdit.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = RowDelete.createFrom;
const $$createType5 = $Create.Array($$createType4);
const $$createType6 = ColumnDef.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $Create.Array($Create.Any);
const $$createType9 = $Create.Map($Create.Any, $Create.Any);
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = ExecutionPlanStep.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = SchemaObjectSummary.createFrom;
const $$createType14 = $Create.Array($$createType13);
const $$createType15 = TypeEntry.createFrom;
const $$createType16 = $Create.Array($$createType15);
