// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    /**
     * "compact" | "normal" | "comfortable"
     */
    "rowDensity": string;

    /**
     * 0 = unlimited
     */
    "defaultRowLimit": number;
    "queryTimeoutSec": number;
    "confirmDropTable": boolean;
    "confirmDeleteRows": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("rowDensity" in $$source)) {
            this["rowDensity"] = "";
        }
        if (!("defaultRowLimit" in $$source)) {
            this["defaultRowLimit"] = 0;
        }
        if (!("queryTimeoutSec" in $$source)) {
            this["queryTimeoutSec"] = 0;
        }
        if (!("confirmDropTable" in $$source)) {
            this["confirmDropTable"] = false;
        }
        if (!("confirmDeleteRows" in $$source)) {
            this["confirmDeleteRows"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class SavedConnection {
    "id": string;
    "name": string;
    "driver": string;
    "connectionString": string;

    /** Creates a new SavedConnection instance. */
    constructor($$source: Partial<SavedConnection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("connectionString" in $$source)) {
            this["connectionString"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedConnection($$parsedSource as Partial<SavedConnection>);
    }
}
