// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function ExecuteQuery(connectionID: string, sql: string): $CancellablePromise<$models.QueryResult> {
    return $Call.ByID(3500987313, connectionID, sql).then(($result: any) => {
        return $$createType0($result);
    });
}

export function ListConnections(): $CancellablePromise<$models.Connection[]> {
    return $Call.ByID(2064096669).then(($result: any) => {
        return $$createType2($result);
    });
}

export function ListSchemaObjects(connectionID: string): $CancellablePromise<$models.SchemaObject[]> {
    return $Call.ByID(1127894517, connectionID).then(($result: any) => {
        return $$createType4($result);
    });
}

// Private type creation functions
const $$createType0 = $models.QueryResult.createFrom;
const $$createType1 = $models.Connection.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.SchemaObject.createFrom;
const $$createType4 = $Create.Array($$createType3);
