// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class Connection {
    "id": string;
    "name": string;
    "driver": string;
    "user": string;
    "host": string;
    "service": string;
    "status": string;
    "lastUsed": string;

    /** Creates a new Connection instance. */
    constructor($$source: Partial<Connection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("user" in $$source)) {
            this["user"] = "";
        }
        if (!("host" in $$source)) {
            this["host"] = "";
        }
        if (!("service" in $$source)) {
            this["service"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("lastUsed" in $$source)) {
            this["lastUsed"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Connection instance from a string or object.
     */
    static createFrom($$source: any = {}): Connection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Connection($$parsedSource as Partial<Connection>);
    }
}

export class ExecutionPlanStep {
    "id": number;
    "operation": string;
    "object": string;
    "cost": number;
    "rows": number;

    /** Creates a new ExecutionPlanStep instance. */
    constructor($$source: Partial<ExecutionPlanStep> = {}) {
        if (!("id" in $$source)) {
            this["id"] = 0;
        }
        if (!("operation" in $$source)) {
            this["operation"] = "";
        }
        if (!("object" in $$source)) {
            this["object"] = "";
        }
        if (!("cost" in $$source)) {
            this["cost"] = 0;
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExecutionPlanStep instance from a string or object.
     */
    static createFrom($$source: any = {}): ExecutionPlanStep {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExecutionPlanStep($$parsedSource as Partial<ExecutionPlanStep>);
    }
}

export class QueryResult {
    "columns": string[];
    "rows": { [_ in string]?: string }[];
    "durationMs": number;
    "message": string;
    "plan": ExecutionPlanStep[];
    "objectStats": SchemaObjectSummary[];

    /** Creates a new QueryResult instance. */
    constructor($$source: Partial<QueryResult> = {}) {
        if (!("columns" in $$source)) {
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            this["rows"] = [];
        }
        if (!("durationMs" in $$source)) {
            this["durationMs"] = 0;
        }
        if (!("message" in $$source)) {
            this["message"] = "";
        }
        if (!("plan" in $$source)) {
            this["plan"] = [];
        }
        if (!("objectStats" in $$source)) {
            this["objectStats"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): QueryResult {
        const $$createField0_0 = $$createType0;
        const $$createField1_0 = $$createType2;
        const $$createField4_0 = $$createType4;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("plan" in $$parsedSource) {
            $$parsedSource["plan"] = $$createField4_0($$parsedSource["plan"]);
        }
        if ("objectStats" in $$parsedSource) {
            $$parsedSource["objectStats"] = $$createField5_0($$parsedSource["objectStats"]);
        }
        return new QueryResult($$parsedSource as Partial<QueryResult>);
    }
}

export class SchemaObject {
    "name": string;
    "type": string;
    "schema": string;
    "rows": number;
    "modified": string;

    /** Creates a new SchemaObject instance. */
    constructor($$source: Partial<SchemaObject> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = "";
        }
        if (!("schema" in $$source)) {
            this["schema"] = "";
        }
        if (!("rows" in $$source)) {
            this["rows"] = 0;
        }
        if (!("modified" in $$source)) {
            this["modified"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaObject instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaObject {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaObject($$parsedSource as Partial<SchemaObject>);
    }
}

export class SchemaObjectSummary {
    "label": string;
    "count": number;

    /** Creates a new SchemaObjectSummary instance. */
    constructor($$source: Partial<SchemaObjectSummary> = {}) {
        if (!("label" in $$source)) {
            this["label"] = "";
        }
        if (!("count" in $$source)) {
            this["count"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaObjectSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): SchemaObjectSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaObjectSummary($$parsedSource as Partial<SchemaObjectSummary>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Map($Create.Any, $Create.Any);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ExecutionPlanStep.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = SchemaObjectSummary.createFrom;
const $$createType6 = $Create.Array($$createType5);
