// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AppSettings {
    /**
     * "compact" | "normal" | "comfortable"
     */
    "rowDensity": string;

    /**
     * 0 = unlimited
     */
    "defaultRowLimit": number;
    "queryTimeoutSec": number;
    "confirmDropTable": boolean;
    "confirmDeleteRows": boolean;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("rowDensity" in $$source)) {
            this["rowDensity"] = "";
        }
        if (!("defaultRowLimit" in $$source)) {
            this["defaultRowLimit"] = 0;
        }
        if (!("queryTimeoutSec" in $$source)) {
            this["queryTimeoutSec"] = 0;
        }
        if (!("confirmDropTable" in $$source)) {
            this["confirmDropTable"] = false;
        }
        if (!("confirmDeleteRows" in $$source)) {
            this["confirmDeleteRows"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class SavedConnection {
    "id": string;
    "name": string;
    "driver": string;
    "connectionString": string;
    "planetscaleKey"?: string;

    /** Creates a new SavedConnection instance. */
    constructor($$source: Partial<SavedConnection> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("driver" in $$source)) {
            this["driver"] = "";
        }
        if (!("connectionString" in $$source)) {
            this["connectionString"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedConnection($$parsedSource as Partial<SavedConnection>);
    }
}

/**
 * SavedTab represents a persisted tab entry in the open_tabs table.
 */
export class SavedTab {
    "id": string;

    /**
     * worksheet | table | schema | sequences | indexes | foreignkeys
     */
    "kind": string;
    "connectionID": string;
    "schemaName": string;
    "tableName": string;
    "name": string;
    "pinned": boolean;
    "sortOrder": number;
    "sqlContent": string;
    "isActive": boolean;

    /** Creates a new SavedTab instance. */
    constructor($$source: Partial<SavedTab> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("connectionID" in $$source)) {
            this["connectionID"] = "";
        }
        if (!("schemaName" in $$source)) {
            this["schemaName"] = "";
        }
        if (!("tableName" in $$source)) {
            this["tableName"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("pinned" in $$source)) {
            this["pinned"] = false;
        }
        if (!("sortOrder" in $$source)) {
            this["sortOrder"] = 0;
        }
        if (!("sqlContent" in $$source)) {
            this["sqlContent"] = "";
        }
        if (!("isActive" in $$source)) {
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SavedTab instance from a string or object.
     */
    static createFrom($$source: any = {}): SavedTab {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SavedTab($$parsedSource as Partial<SavedTab>);
    }
}
