// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service for all app-level persistence: settings and
 * saved connection profiles, backed by the GORM SQLite store.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * DeleteSavedConnection removes a saved connection by ID.
 */
export function DeleteSavedConnection(id: string): $CancellablePromise<void> {
    return $Call.ByID(2902567615, id);
}

export function GetSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3606267844).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * ListSavedConnections returns all persisted connection profiles.
 */
export function ListSavedConnections(): $CancellablePromise<$models.SavedConnection[]> {
    return $Call.ByID(2555710255).then(($result: any) => {
        return $$createType2($result);
    });
}

export function LoadTabs(): $CancellablePromise<$models.SavedTab[]> {
    return $Call.ByID(2204960759).then(($result: any) => {
        return $$createType4($result);
    });
}

export function SaveSettings(settings: $models.AppSettings): $CancellablePromise<void> {
    return $Call.ByID(3401768143, settings);
}

export function SaveTabs(tabs: $models.SavedTab[]): $CancellablePromise<void> {
    return $Call.ByID(2757083582, tabs);
}

/**
 * UpdateSavedConnection persists changes to an existing connection.
 */
export function UpdateSavedConnection(conn: $models.SavedConnection): $CancellablePromise<void> {
    return $Call.ByID(2426149905, conn);
}

// Private type creation functions
const $$createType0 = $models.AppSettings.createFrom;
const $$createType1 = $models.SavedConnection.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = $models.SavedTab.createFrom;
const $$createType4 = $Create.Array($$createType3);
