// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AvailableConnection is a provider-hosted database not yet saved locally.
 */
export class AvailableConnection {
    /**
     * "planetscale" | "supabase"
     */
    "Provider": string;

    /**
     * provider-specific unique key (ref or org/name/branch)
     */
    "Key": string;
    "Name": string;

    /**
     * e.g. "myorg · main" or "us-west-1"
     */
    "Meta": string;
    "NeedsPassword": boolean;

    /**
     * Internal params used by Connect — opaque to the frontend.
     */
    "Org": string;
    "Branch": string;
    "Kind": string;

    /** Creates a new AvailableConnection instance. */
    constructor($$source: Partial<AvailableConnection> = {}) {
        if (!("Provider" in $$source)) {
            this["Provider"] = "";
        }
        if (!("Key" in $$source)) {
            this["Key"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Meta" in $$source)) {
            this["Meta"] = "";
        }
        if (!("NeedsPassword" in $$source)) {
            this["NeedsPassword"] = false;
        }
        if (!("Org" in $$source)) {
            this["Org"] = "";
        }
        if (!("Branch" in $$source)) {
            this["Branch"] = "";
        }
        if (!("Kind" in $$source)) {
            this["Kind"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AvailableConnection instance from a string or object.
     */
    static createFrom($$source: any = {}): AvailableConnection {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AvailableConnection($$parsedSource as Partial<AvailableConnection>);
    }
}
