// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service aggregates provider accounts and exposes a unified connection API.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * Connect fetches (or reuses) a connection string for the given available connection.
 * password is only used for Supabase; pass "" for PlanetScale.
 */
export function Connect(ac: $models.AvailableConnection, password: string): $CancellablePromise<string> {
    return $Call.ByID(3227457396, ac, password);
}

/**
 * ListAvailable returns all provider databases/projects that are not yet saved as connections.
 */
export function ListAvailable(): $CancellablePromise<$models.AvailableConnection[]> {
    return $Call.ByID(3191806913).then(($result: any) => {
        return $$createType1($result);
    });
}

// Private type creation functions
const $$createType0 = $models.AvailableConnection.createFrom;
const $$createType1 = $Create.Array($$createType0);
