// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service that exposes PlanetScale OAuth and database
 * discovery to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConnectionString returns a postgres:// connection string for the given
 * database branch. Reuses saved credentials when available; otherwise creates
 * new credentials and saves them.
 */
export function GetConnectionString(org: string, database: string, branch: string, kind: string): $CancellablePromise<string> {
    return $Call.ByID(3161479877, org, database, branch, kind);
}

/**
 * GetUser returns the display name and email of the signed-in PlanetScale user
 * by reading from the local store — no network call.
 */
export function GetUser(): $CancellablePromise<$models.User> {
    return $Call.ByID(878342871).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsSignedIn returns true if a valid PlanetScale token is stored.
 */
export function IsSignedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(1194748295);
}

/**
 * ListDatabases returns all PlanetScale database branches accessible to the signed-in user.
 */
export function ListDatabases(): $CancellablePromise<$models.Database[]> {
    return $Call.ByID(2809943722).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SignOut clears the stored PlanetScale token and user info.
 */
export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(1100415763);
}

export function StartAuth(): $CancellablePromise<void> {
    return $Call.ByID(4271875474);
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
const $$createType1 = $models.Database.createFrom;
const $$createType2 = $Create.Array($$createType1);
