// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Project is the Wails-facing type for a connectable Supabase project.
 */
export class Project {
    "Ref": string;
    "Name": string;
    "Region": string;
    "Status": string;

    /** Creates a new Project instance. */
    constructor($$source: Partial<Project> = {}) {
        if (!("Ref" in $$source)) {
            this["Ref"] = "";
        }
        if (!("Name" in $$source)) {
            this["Name"] = "";
        }
        if (!("Region" in $$source)) {
            this["Region"] = "";
        }
        if (!("Status" in $$source)) {
            this["Status"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Project instance from a string or object.
     */
    static createFrom($$source: any = {}): Project {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Project($$parsedSource as Partial<Project>);
    }
}

/**
 * User is the Wails-facing type for the signed-in Supabase account.
 */
export class User {
    "DisplayName": string;
    "Email": string;

    /** Creates a new User instance. */
    constructor($$source: Partial<User> = {}) {
        if (!("DisplayName" in $$source)) {
            this["DisplayName"] = "";
        }
        if (!("Email" in $$source)) {
            this["Email"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new User instance from a string or object.
     */
    static createFrom($$source: any = {}): User {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new User($$parsedSource as Partial<User>);
    }
}
