// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Service is the Wails service that exposes Supabase OAuth and project
 * discovery to the frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * GetConnectionString builds a connection string for the given Supabase project.
 * It does NOT save — the caller must pass the returned string and the project ref
 * (as supabaseKey) to db.Connect, which saves only on successful connection.
 */
export function GetConnectionString(ref: string, name: string, password: string): $CancellablePromise<string> {
    return $Call.ByID(3825434642, ref, name, password);
}

/**
 * GetUser returns the display name and email of the signed-in Supabase user
 * by reading from the local store — no network call.
 */
export function GetUser(): $CancellablePromise<$models.User> {
    return $Call.ByID(1279450524).then(($result: any) => {
        return $$createType0($result);
    });
}

/**
 * IsSignedIn returns true if a valid Supabase token is stored.
 */
export function IsSignedIn(): $CancellablePromise<boolean> {
    return $Call.ByID(1961843510);
}

/**
 * ListProjects returns all Supabase projects accessible to the signed-in user.
 * It automatically refreshes the access token if the initial request fails.
 */
export function ListProjects(): $CancellablePromise<$models.Project[]> {
    return $Call.ByID(2399471043).then(($result: any) => {
        return $$createType2($result);
    });
}

/**
 * SignOut clears the stored Supabase token and user info.
 */
export function SignOut(): $CancellablePromise<void> {
    return $Call.ByID(2621664464);
}

export function StartAuth(): $CancellablePromise<void> {
    return $Call.ByID(110220865);
}

// Private type creation functions
const $$createType0 = $models.User.createFrom;
const $$createType1 = $models.Project.createFrom;
const $$createType2 = $Create.Array($$createType1);
